import { Transaction } from '../types';

/**
 * 60+ days of realistic historical ledger data for a professional crypto trading bot operation.
 * Covers:
 * - Starting capital deposit ($50,000 USDT)
 * - Loan drawdown ($20,000 USDT credit line)
 * - Multiple bots: BTC-Grid-01, ETH-DCA-Trend, SOL-Funding-Arb, AVAX-MeanRevert
 * - Real on-chain and exchange gas/fees
 * - Periodic interest accrual / payments
 * - Partial loan repayment
 * - Periodic profit withdrawals to cold storage
 */
export const INITIAL_SAMPLE_TRANSACTIONS: Transaction[] = [
  // Day 1: Initial Capital Injection
  {
    id: 'tx-001',
    date: '2026-07-01',
    type: 'Deposit',
    amount: 50000,
    asset: 'USDT',
    sourceDest: 'Bank / Wire -> Binance',
    gasFee: 15,
    botId: 'Treasury',
    notes: 'Initial business seed capital allocation',
  },
  // Day 3: Loan Drawdown for working capital
  {
    id: 'tx-002',
    date: '2026-07-03',
    type: 'Loan In',
    amount: 20000,
    asset: 'USDC',
    sourceDest: 'Institutional Credit Desk -> Bybit',
    gasFee: 12,
    botId: 'Treasury',
    notes: '6-month working capital credit facility at 7% APR',
  },
  // Day 4: Bot 1 Starts (BTC-Grid)
  {
    id: 'tx-003',
    date: '2026-07-04',
    type: 'Trade PnL',
    amount: 340.5,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 6.8,
    botId: 'BTC-Grid-01',
    notes: '28 grid executions during rangebound consolidation',
  },
  // Day 5
  {
    id: 'tx-004',
    date: '2026-07-05',
    type: 'Trade PnL',
    amount: 412.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 8.2,
    botId: 'BTC-Grid-01',
    notes: 'Grid rebalance during morning volatility spike',
  },
  {
    id: 'tx-005',
    date: '2026-07-05',
    type: 'Trade PnL',
    amount: 185.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.5,
    botId: 'SOL-Funding-Arb',
    notes: 'Delta-neutral funding rate yield collection',
  },
  // Day 6
  {
    id: 'tx-006',
    date: '2026-07-06',
    type: 'Trade PnL',
    amount: -210.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 5.4,
    botId: 'ETH-DCA-Trend',
    notes: 'Trailing stop triggered on false breakout',
  },
  {
    id: 'tx-007',
    date: '2026-07-06',
    type: 'Gas',
    amount: 28.5,
    asset: 'ETH',
    sourceDest: 'Ethereum L1 Wallet',
    gasFee: 0,
    botId: 'System',
    notes: 'Rebalance liquidity across L1 bridge to Arbitrum',
  },
  // Day 7
  {
    id: 'tx-008',
    date: '2026-07-07',
    type: 'Trade PnL',
    amount: 520.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 10.4,
    botId: 'BTC-Grid-01',
    notes: 'High volume day, 42 roundtrip fills',
  },
  {
    id: 'tx-009',
    date: '2026-07-07',
    type: 'Trade PnL',
    amount: 310.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 2.1,
    botId: 'SOL-Funding-Arb',
    notes: 'Funding rate 0.03% 8h annualized 32%',
  },
  // Day 8
  {
    id: 'tx-010',
    date: '2026-07-08',
    type: 'Trade PnL',
    amount: 680.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 12.0,
    botId: 'ETH-DCA-Trend',
    notes: 'Target 1 hit on ETH 4h continuation setup',
  },
  // Day 10
  {
    id: 'tx-011',
    date: '2026-07-10',
    type: 'Trade PnL',
    amount: -140.0,
    asset: 'USDT',
    sourceDest: 'OKX Swap',
    gasFee: 4.2,
    botId: 'AVAX-MeanRevert',
    notes: 'Slippage during liquidation cascade',
  },
  {
    id: 'tx-012',
    date: '2026-07-10',
    type: 'Trade PnL',
    amount: 290.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 5.8,
    botId: 'BTC-Grid-01',
    notes: 'Lower grid boundaries absorbed bounce',
  },
  // Day 12
  {
    id: 'tx-013',
    date: '2026-07-12',
    type: 'Trade PnL',
    amount: 440.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.8,
    botId: 'SOL-Funding-Arb',
    notes: 'Positive funding settlement across weekend',
  },
  {
    id: 'tx-015',
    date: '2026-07-15',
    type: 'Trade PnL',
    amount: 890.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 15.2,
    botId: 'ETH-DCA-Trend',
    notes: 'Trend runner hit take-profit level 2',
  },
  // Day 18
  {
    id: 'tx-016',
    date: '2026-07-18',
    type: 'Trade PnL',
    amount: 360.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 7.2,
    botId: 'BTC-Grid-01',
    notes: 'Normal grid churn',
  },
  {
    id: 'tx-017',
    date: '2026-07-18',
    type: 'Trade PnL',
    amount: 215.0,
    asset: 'USDT',
    sourceDest: 'OKX Swap',
    gasFee: 3.8,
    botId: 'AVAX-MeanRevert',
    notes: 'Bollinger band mean reversion close',
  },
  // Day 21
  {
    id: 'tx-018',
    date: '2026-07-21',
    type: 'Trade PnL',
    amount: -320.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 6.5,
    botId: 'ETH-DCA-Trend',
    notes: 'Chop stopout',
  },
  {
    id: 'tx-019',
    date: '2026-07-21',
    type: 'Trade PnL',
    amount: 275.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.2,
    botId: 'SOL-Funding-Arb',
    notes: 'Weekly funding credit',
  },
  // Day 25: First Profit Withdrawal to Bank/Cold Storage
  {
    id: 'tx-020',
    date: '2026-07-25',
    type: 'Withdrawal',
    amount: 3500.0,
    asset: 'USDT',
    sourceDest: 'Binance -> Ledger Cold Storage',
    gasFee: 8.0,
    botId: 'Treasury',
    notes: 'Realized profit harvest taking principal off risk table',
  },
  // Day 28
  {
    id: 'tx-021',
    date: '2026-07-28',
    type: 'Trade PnL',
    amount: 620.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 11.5,
    botId: 'BTC-Grid-01',
    notes: 'Heavy volatility session 54 fills',
  },
  // August Data (Month 2)
  {
    id: 'tx-023',
    date: '2026-08-02',
    type: 'Trade PnL',
    amount: 450.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 9.0,
    botId: 'ETH-DCA-Trend',
    notes: 'Trend breakout entry confirmed on 1h',
  },
  {
    id: 'tx-024',
    date: '2026-08-03',
    type: 'Trade PnL',
    amount: 310.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.9,
    botId: 'SOL-Funding-Arb',
    notes: 'Funding arbitrage cycle completed',
  },
  {
    id: 'tx-025',
    date: '2026-08-06',
    type: 'Trade PnL',
    amount: 510.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 10.2,
    botId: 'BTC-Grid-01',
    notes: 'Consistent daily grid accumulation',
  },
  // Day 40: Partial Loan Repayment
  {
    id: 'tx-026',
    date: '2026-08-10',
    type: 'Loan Out',
    amount: 5000.0,
    asset: 'USDC',
    sourceDest: 'Bybit -> Credit Desk Principal',
    gasFee: 6.0,
    botId: 'Treasury',
    notes: 'Deleveraging: Repaid $5,000 of loan principal from bot earnings',
  },
  {
    id: 'tx-027',
    date: '2026-08-12',
    type: 'Trade PnL',
    amount: -180.0,
    asset: 'USDT',
    sourceDest: 'OKX Swap',
    gasFee: 4.0,
    botId: 'AVAX-MeanRevert',
    notes: 'Stopped out at 2.5% max risk threshold',
  },
  {
    id: 'tx-028',
    date: '2026-08-14',
    type: 'Trade PnL',
    amount: 740.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 14.8,
    botId: 'ETH-DCA-Trend',
    notes: 'Strong weekly close continuation trade',
  },
  {
    id: 'tx-030',
    date: '2026-08-18',
    type: 'Trade PnL',
    amount: 380.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 7.6,
    botId: 'BTC-Grid-01',
    notes: 'Grid engine stable',
  },
  {
    id: 'tx-031',
    date: '2026-08-20',
    type: 'Trade PnL',
    amount: 295.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.5,
    botId: 'SOL-Funding-Arb',
    notes: 'Funding fee harvest',
  },
  {
    id: 'tx-032',
    date: '2026-08-24',
    type: 'Withdrawal',
    amount: 4000.0,
    asset: 'USDT',
    sourceDest: 'Bybit -> Business Operating Account',
    gasFee: 10.0,
    botId: 'Treasury',
    notes: 'Quarterly tax reserve & partner distributions',
  },
  {
    id: 'tx-033',
    date: '2026-08-28',
    type: 'Trade PnL',
    amount: 820.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 16.4,
    botId: 'BTC-Grid-01',
    notes: 'High volatility grid harvesting 68 executions',
  },
  // September Data (Current Month)
  {
    id: 'tx-035',
    date: '2026-09-02',
    type: 'Trade PnL',
    amount: 410.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 8.2,
    botId: 'ETH-DCA-Trend',
    notes: 'Momentum swing take-profit 1',
  },
  {
    id: 'tx-036',
    date: '2026-09-05',
    type: 'Trade PnL',
    amount: 320.0,
    asset: 'USDC',
    sourceDest: 'Hyperliquid Perp',
    gasFee: 1.7,
    botId: 'SOL-Funding-Arb',
    notes: 'Funding arbitrage rate 28% annualized',
  },
  {
    id: 'tx-037',
    date: '2026-09-08',
    type: 'Trade PnL',
    amount: -125.0,
    asset: 'USDT',
    sourceDest: 'OKX Swap',
    gasFee: 3.5,
    botId: 'AVAX-MeanRevert',
    notes: 'Small whipsaw loss on false trendline breakout',
  },
  {
    id: 'tx-038',
    date: '2026-09-12',
    type: 'Trade PnL',
    amount: 540.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 10.8,
    botId: 'BTC-Grid-01',
    notes: 'BTC support bounce 35 grid fills',
  },
  {
    id: 'tx-040',
    date: '2026-09-18',
    type: 'Trade PnL',
    amount: 670.0,
    asset: 'USDT',
    sourceDest: 'Bybit Linear',
    gasFee: 13.4,
    botId: 'ETH-DCA-Trend',
    notes: 'ETH breakout target 2 hit',
  },
  {
    id: 'tx-041',
    date: '2026-09-21',
    type: 'Trade PnL',
    amount: 395.0,
    asset: 'USDT',
    sourceDest: 'Binance Spot',
    gasFee: 7.9,
    botId: 'BTC-Grid-01',
    notes: 'Ongoing automated grid trade cycles',
  },
];

export const SAMPLE_TRANSACTIONS = INITIAL_SAMPLE_TRANSACTIONS;
